# dataset
data_dir: "/data/datasets/DVS/ES-imagenet-0.18/extract/ES-imagenet-0.18/"
dataset: esimnet
num_classes: 1000
img_size: 224

#data augmentation


# model structure
model: "spikformer_es"
step: 10
in_channels: 2
embed_dim: 384
num_heads: 12
mlp_ratio: 4
attn_scale: 0.125
mlp_drop: 0.0
attn_drop: 0.0
depths: 4


# node
tau: 2.0
threshold: 1.0
act_function: SigmoidGrad
node_type: LIFNode
alpha: 4.0


batch_size: 16
lr: 5e-4
min_lr: 1e-5
sched: cosine
weight_decay: 6e-2
cooldown_epochs: 10
warmup_epochs: 10
warmup_lr: 0.00001
opt: adamw
smoothing: 0.1
workers: 4
epochs: 500   #epochs
seed: 41
log_interval: 200

# device
device: 3

# log dir
output: "/home/shensicheng/log/SpikingTransformerBenchmark/cls/"