# dataset
data_dir: "/data/datasets/DVS/DVS_Cifar10/"
dataset: dvsc10
num_classes: 10
event_size: 64
patch_size: 16

#data augmentation

epochs: 300   #epochs

# model structure
model: "tim"
step: 10
in_channels: 2
embed_dim: 256
num_heads: 16
mlp_ratio: 4
attn_scale: 0.25
mlp_drop: 0.0
attn_drop: 0.0
depths: 2

# tim special params
tim_alpha: 0.5

# node
tau: 2.0
threshold: 1.0
act_function: SigmoidGrad
node_type: LIFNode
alpha: 4.0
