# default training hyperparam
## for cifar10/100
batch_size: 16
lr: 5e-4
min_lr: 1e-5
sched: cosine
weight_decay: 6e-2
cooldown_epochs: 10
warmup_epochs: 10
warmup_lr: 0.00001
opt: adamw
smoothing: 0.1
workers: 4
seed: 41



## you may change the params below
# change your device here
device: 0
# display interval in terminal
log_interval: 200
# log dir
output: "/home/shensicheng/log/SpikingTransformerBenchmark/cls/"