# for cifar10/100
amp: True
batch_size: 64
val_batch_size: 64
lr: 1e-3
min_lr: 1e-5
sched: cosine
weight_decay: 6e-2
cooldown_epochs: 10
warmup_epochs: 20
warmup_lr: 0.00001
opt: adamw
smoothing: 0.1
workers: 8
depths: 4
seed: 42


## you may change the params below
# change your device here
device: 7
# display interval in terminal
log_interval: 200
# log dir
output: "/home/shensicheng/log/SpikingTransformerBenchmark/cls/"