aa: rand-m9-mstd0.5-inc1
act_function: SigmoidGrad
alpha: 4.0
amp: true
apex_amp: false
attn_drop: 0.0
attn_scale: 0.125
aug_splits: 0
batch_size: 48
bn_eps: null
bn_momentum: null
bn_tf: false
channels_last: false
checkpoint_hist: 10
clip_grad: null
clip_mode: norm
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: 1.0
cutmix: 1.0
cutmix_minmax: null
data_dir: /mnt/data/datasets/ILSVRC2012
dataset: imagenet
decay_epochs: 30
decay_rate: 0.1
depths: 10
device: 0
dist_bn: ''
drop: 0.0
drop_block: null
drop_connect: null
drop_path: null
embed_dim: 384
epoch_repeats: 0.0
epochs: 300
eval_metric: top1
event_mix: false
experiment: ''
gp: null
hflip: 0.5
img_size: 224
in_channels: 3
initial_checkpoint: ''
input_size: null
interpolation: bicubic
jsd: false
local_rank: 0
log_interval: 1000
log_wandb: false
lr: 0.0005
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean:
- 0.485
- 0.456
- 0.406
min_lr: 1.0e-05
mixup: 0.8
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
mlp_drop: 0.0
mlp_ratio: 4
model: qkformer_imagenet
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
momentum: 0.9
native_amp: false
no_aug: false
no_prefetcher: false
no_resume_opt: false
node_type: LIFNode
num_classes: 1000
num_heads: 6
opt: adamw
opt_betas: null
opt_eps: null
output: ./
patch_size: 16
patience_epochs: 10
pin_mem: false
pretrained: false
ratio:
- 1.0
- 1.0
recount: 1
recovery_interval: 0
remode: const
reprob: 0.25
resplit: false
resume: ''
save_images: false
scale:
- 1.0
- 1.0
sched: cosine
seed: 42
smoothing: 0.1
split_bn: false
start_epoch: null
std:
- 0.229
- 0.224
- 0.225
step: 4
sync_bn: false
tau: 2.0
threshold: 1.0
torchscript: false
train_interpolation: bicubic
train_split: train
tta: 0
use_multi_epochs_loader: false
val_batch_size: 48
val_split: validation
vflip: 0.0
warmup_epochs: 20
warmup_lr: 1.0e-06
weight_decay: 0.05
workers: 8
